# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcalendarcore': '@latest-kf6'
    'frameworks/kcolorscheme': '@latest-kf6'
    'graphics/kdiagram': '@latest-kf6'
    'pim/akonadi': '@same'
    'pim/akonadi-calendar': '@same'
    'pim/calendarsupport': '@same'
    'pim/kcalutils': '@same'
    'pim/kmime': '@same'
    'pim/libkdepim': '@same'

Options:
 cmake-options: '-DKDEPIM_BUILD_EXAMPLES=ON'
 require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
 tests-run-in-parallel: True
