# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcalendarcore' : '@latest'
    'frameworks/kconfigwidgets' : '@latest'
    'graphics/kdiagram' : '@latest'
    'pim/akonadi' : '@same'
    'pim/akonadi-calendar' : '@same'
    'pim/calendarsupport' : '@same'
    'pim/kcalutils' : '@same'
    'pim/kmime' : '@same'
    'pim/libkdepim' : '@same'

Options:
  cmake-options: '-DKDEPIM_BUILD_EXAMPLES=ON'
  require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows' ]
