# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcalendarcore' : '@latest'
    'frameworks/kconfigwidgets' : '@latest'
    'extragear/graphics/kdiagram' : '@latest'
    'pim/akonadi' : '@same'
    'pim/akonadi-calendar' : '@same'
    'pim/calendarsupport' : '@same'
    'pim/kcalutils' : '@same'
    'pim/kmime' : '@same'
    'pim/libkdepim' : '@same'
